### ISSUE TITLE
11/28 warrior issue

### ISSUE THREAD

**Issue by Elminster067** [Vae2009/ConRO_Warrior#1]
good morning, last night i noticed you fixed the warrior, loged in this morning and this is the first thing that pops up

Message: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
Time: Mon Nov 28 07:34:47 2022
Count: 3
Stack: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:895: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:98: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:526: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2389: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

and 

Message: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
Time: Mon Nov 28 07:34:46 2022
Count: 2
Stack: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:895: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:98: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:526: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2389: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConRO/buttons.lua"]:2186: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

I do not have ace, do i need ace3?

**Comment by Elminster067** [comment]
after closing the Lua error box, mounted and this pops up

Message: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
Time: Mon Nov 28 07:43:30 2022
Count: 2
Stack: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:895: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:98: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:526: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2389: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConRO/buttons.lua"]:2186: in function `?'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

and 

Message: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
Time: Mon Nov 28 07:43:30 2022
Count: 3
Stack: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:895: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:98: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:526: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2389: in function `?'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

**Comment by Elminster067** [comment]
ya had to disable the mod

**Comment by Vae2009** [comment]
Are these issue still happening? with the new versions of both ConRO and Warrior?

**Comment by Elminster067** [comment]
I didn't check till now because I haven't seen an update on ether of them on curse forge app I had both turned off because it spammed the errors above, I have all mods off because one of them is interfering with dragon isle summery on the mini map.  I turned yours on and this is the error today

Message: Interface/AddOns/ConRO/helper.lua:28: attempt to index local 'configInfo' (a nil value)
Time: Tue Nov 29 23:20:43 2022
Count: 1
Stack: Interface/AddOns/ConRO/helper.lua:28: attempt to index local 'configInfo' (a nil value)
[string "@Interface/AddOns/ConRO/helper.lua"]:28: in function `CheckTalents'
[string "@Interface/AddOns/ConRO/core.lua"]:2050: in function `EnableRotation'
[string "@Interface/AddOns/ConRO/core.lua"]:2310: in function `?'
[string "@Interface/AddOns/ConRO/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...nRO/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/ConRO/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...nRO/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/ConRO/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ConRO/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/ConRO/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

as soon as i logged in, and I tried fighting a mob and it popped up again, 2 x each

**Comment by Elminster067** [comment]
i am trying to learn lua, i bought a couple books on it so I can try my hand at mods for wow

**Comment by Elminster067** [comment]
but i have been busy catching up since i haven't played a while, got all my toons to level 60 before Monday and 260 gear score on each of them. and of course i use your mod for each of them :)

**Comment by Elminster067** [comment]
![cconro](https://user-images.githubusercontent.com/119313387/204708489-4a11e38e-a248-4192-8fc0-f0258d2b49d9.png)

**Comment by Vae2009** [comment]
Same issue in another thread
