### ISSUE TITLE
LUA Error while Dragonriding

### ISSUE THREAD

**Issue by dakota102003** [Vae2009/ConRO_Warrior#2]
Getting this when on any new dragonriding mount.

27364x ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: in function `GetSpellCooldown'
[string "@ConRO/helper.lua"]:895: in function `Cooldown'
[string "@ConRO/helper.lua"]:98: in function `FullMode'
[string "@ConRO_Warrior/warrior.lua"]:732: in function `NextSpell'
[string "@ConRO/core.lua"]:2389: in function `?'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = false

**Comment by Vae2009** [comment]
That is odd, can you post the version of ConRO and ConRO Warrior that you are using?

**Comment by dakota102003** [comment]
Main version 10.0.6
Warrior version 10.0.1

Both from Curse

sorry for late response.

**Comment by Elminster067** [comment]
same error i am getting

**Comment by Elminster067** [comment]
i think it is because when you mount your dragon in the dragon isles it changes the main spell bars.  I am using blizzard default bars

**Comment by Elminster067** [comment]
![WoWScrnShot_120122_080237](https://user-images.githubusercontent.com/119313387/205059834-f3d27503-988c-4d0d-9f5a-1441716f90fe.jpg)
![WoWScrnShot_120122_080244](https://user-images.githubusercontent.com/119313387/205059872-f53b45be-0c2c-4e3a-9114-3a0816205dce.jpg)

**Comment by Elminster067** [comment]
I tried changing the my skills to the bottom bar and changed the hotkeys and the error still pops up

**Comment by Elminster067** [comment]
it pops up when you get on any mount

**Comment by Elminster067** [comment]
I tried it on 4 other toons as well, it only happens to the warrior that i can see.

**Comment by Vae2009** [comment]
I have not been able to test this issue, but I have uploaded a hopeful fix with ConRO v 10.0.7. If you can let me know if this works please.

**Comment by Elminster067** [comment]
nope still getting it, 

Message: Interface/AddOns/ConRO/helper.lua:892: GetSpellCooldown(): Invalid spell slot
Time: Thu Dec  1 17:28:40 2022
Count: 2
Stack: Interface/AddOns/ConRO/helper.lua:892: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:892: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:95: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:732: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2409: in function `?'
[string "@Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...face/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: (*temporary) = false

and 

Message: Interface/AddOns/ConRO/helper.lua:892: GetSpellCooldown(): Invalid spell slot
Time: Thu Dec  1 17:29:33 2022
Count: 2
Stack: Interface/AddOns/ConRO/helper.lua:892: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:892: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:95: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:732: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2409: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConRO/buttons.lua"]:2186: in function `?'
[string "@Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...face/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: (*temporary) = false

**Comment by Elminster067** [comment]
as soon as i log in, and when i get on a mount and dismount, i am going to try deleting the warrior file and redownload it when i get back from dropping my daughter off at Karate

**Comment by Elminster067** [comment]
deleted both and reinstall the new version of conro and warrior and still getting the message

**Comment by Elminster067** [comment]
getting this when i target things

Message: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
Time: Thu Dec  1 18:18:52 2022
Count: 1
Stack: Interface/AddOns/ConRO/helper.lua:895: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:895: in function `Cooldown'
[string "@Interface/AddOns/ConRO/helper.lua"]:98: in function `FullMode'
[string "@Interface/AddOns/ConRO_Warrior/warrior.lua"]:732: in function `NextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2389: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConRO/core.lua"]:2324: in function `?'
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/ConRO/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/ConRO/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: <none>

**Comment by Vae2009** [comment]
Can you link me your talent build from the "Share" option in the lower left hand corner please.

**Comment by Elminster067** [comment]
I have 3 builds, one for raids, one for mythic and one for leveling. this is the raid build

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSCJJk0SKJSKNEhIUEClkEgIkE0CJJgAhAAAAAAAAJBAgSpBA

**Comment by Elminster067** [comment]
this is the level build

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQikSikWBRgAJSUSSAiEJBtQSCAECAAAAAAAkEAAKlGA

**Comment by Elminster067** [comment]
and this is the mythic build 

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQikSikWBRgQRiElkEgAJBtQSCIQIAAAAAAAQSAAoUaA

it does it for all 3

**Comment by Elminster067** [comment]
i get my builds from here and they are not bad  i think, but i havnt played wow in a few years

**Comment by Elminster067** [comment]
all the builds above are tank builds.  it does it on fury and protection. it doesn't seem to do it on arms

**Comment by Elminster067** [comment]
builds i get from here https://www.wowhead.com/guide/classes/warrior/protection/talent-builds-pve-tank  sorry forgot to paste it before

**Comment by Elminster067** [comment]
ya, no error messages on arms

**Comment by Elminster067** [comment]
still errors on war, Fury talent build and Protection, arms talent  build was working last i checked

**Comment by Vae2009** [comment]
Found a global taint in ConRO:CoolDown() ... hopefully ConRO v10.0.11 will resolve

**Comment by Elminster067** [comment]
nope, tried it this morning, works while in arms talent build but not Protection

**Comment by Elminster067** [comment]
works for my hunter and evoker as well btw

**Comment by Vae2009** [comment]
Issue has been found

**Comment by Elminster067** [comment]
works now, thanks :)
